Update symfony.yml

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -1,42 +1,64 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-
-name: Symfony CI
+ name: CI Build / Merge
 
 on:
   push:
     branches:
-        - main
+      - feature/* # toutes les branches doivent commencer par feature/
   pull_request:
     branches:
-        - main
+      - master
+
 jobs:
-  test:
-    runs-on: ubuntu-latest
+  build_merge:
+    runs-on: ubuntu-latest  # tester sur un environnement stable
 
     steps:
-      # 1. Checkout le code source
-      
-       - name: Checkout code
-         uses: actions/checkout@v3
-        
-              # 2. Installer PHP
-       - name: Set up PHP
-         uses: shivammathur/setup-php@v2
-         with:
-          php-version: '8.3'
-          coverage: xdebug 
-        
-              # 3. Installer les dépendances avec Composer
-              
-       - name: Install dependencies
-         run: |
-                composer install --no-interaction --prefer-dist
-        
-              # 4. Exécuter les tests avec PHPUnit
-              
-       - name: Run PHPUnit tests
-         run: |
-                vendor/bin/phpunit --configuration phpunit.xml.dist --strict
+    - name: Checkout le code
+      uses: actions/checkout@v2
+
+    - name: Paramétrer PHP 8.3
+      uses: shivammathur/setup-php@v2
+      with:
+        php-version: '8.3'
+
+    - name: Installer les dépendances composer
+      run: |
+        curl -sS https://getcomposer.org/installer | php
+        php composer.phar install
+
+    - name: Paramétrer Node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: '20' 
+
+    - name: Installer les dépendances npm
+      run: |
+        npm install
+
+    - name: Build Tailwind CSS
+      run: |
+        npx tailwindcss -o public/css/tailwind.css  # Compile Tailwind CSS dans public/css/tailwind.css
+
+    - name: Lancer PHP Lint pour vérifier les erreurs de syntaxe PHP
+      run: |
+        find . -name "*.php" -exec php -l {} \;
+
+    - name: Commit si succès
+      run: |
+        git config --global user.name "GreenScoreWebPlugin"
+        git config --global user.email "greenscore.plugin@gmail.com"
+        git add .
+        git commit -m "Commit automatique réussi" || echo "No changes to commit"
+
+    - name: Merge vers master
+      run: |
+        git checkout master
+        git pull origin master
+        git merge ${{ github.head_ref }} --no-ff -m "Merge la branche dans master"
+        git push origin master
+
+    - name: Créer une erreur si fail
+      if: failure()
+      run: |
+        echo "Build failed. Exiting."
+        exit 1
